sudo: required

services:
  - docker

before_install:
  - docker build -t tpdock/freeradius:latest .

script: true

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push tpdock/freeradius:latest

